# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a03f4b0e86680dcc46e75695bb463b793a9a72a040e99f136c1aa2e648efa5f8f9b934c74545268ba89dafab43b27e4052a24d92c92f10e9444e06141f638f4

test:
  secret_key_base: cce4cd0b22ab20f4d3cc7349bb11b72190ad7297f484569e9e8675f352daf29cf1a1014bd8bca6d5a47c20ef9717eec7ffc117d01e34732af26bb10394382a98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
